# Generated by Django 3.2.5 on 2021-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('payload', models.CharField(max_length=300)),
                ('utc_date', models.DateTimeField()),
                ('status', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('operator_name', models.CharField(max_length=20)),
                ('operator_group', models.CharField(max_length=20)),
                ('store_id', models.IntegerField()),
            ],
        ),
    ]
