# Generated by Django 3.2.5 on 2021-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='conversation_id',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
    ]
