# Generated by Django 3.2.5 on 2021-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chat_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='operator_group',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='operator_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='store_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
