# Generated by Django 3.2.5 on 2021-07-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210711_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='client_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='operator_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
