# Generated by Django 3.2.5 on 2021-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210711_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
