# Generated by Django 3.2.5 on 2021-07-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210712_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='conversation_id',
            field=models.IntegerField(),
        ),
    ]
